type Hand = "LH" | "RH";

type CoatingLayoutEndBitProps = {
  hand: Hand;
  fullLengthRuns?: number; // 0-5
  shoulderRuns?: number; // 0-5
};

const COATING_COLOUR = "#f97316";
const LINE_COLOUR = "#111827";
const STEEL_FILL = "#e5e7eb";

// Traced directly from the user's confirmed reference sketch — this
// shape does NOT scale from length/width/thickness formulas like the
// straight-edge model. It's a fixed template shared across a linked
// group of part numbers (dimensions vary per part number, but the
// proportions are close enough that one traced template represents
// the whole group). RH coordinates are the source of truth; LH is
// generated by mirroring (x -> 700 - x), matching how the user
// confirmed the two hands in the sketch pad.
const RH_OUTLINE: [number, number][] = [
  [562, 96], [296, 101], [261, 210], [248, 258], [264, 293],
  [300, 298], [355, 284], [446, 268], [562, 257],
];

const RH_HOLES: [number, number][] = [
  [506, 131], [524, 171], [488, 171],
  [393, 129], [354, 127], [386, 169], [346, 168],
];

// Runs 1-5: full-length runs, following the tapered/rounded working
// edge, stacking further inward from the edge as the count increases.
const RH_FULL_LENGTH_RUNS: [number, number][][] = [
  [[265, 287], [287, 289], [308, 289], [344, 280], [442, 261], [556, 249]],
  [[260, 275], [297, 277], [323, 274], [440, 250], [557, 238]],
  [[255, 264], [308, 264], [434, 240], [558, 227]],
  [[251, 253], [308, 253], [431, 229], [557, 218]],
  [[258, 241], [307, 241], [429, 219], [557, 208]],
];

// Runs 6-10: shoulder runs — short standard-length strips (~100mm)
// that sit immediately above/inward of wherever the full-length runs
// stop, not a fixed slot. Rendering shows shoulderRuns[0] immediately
// above whichever full-length run is currently the last one shown.
const RH_SHOULDER_RUNS: [number, number][][] = [
  [[259, 228], [305, 229]],
  [[262, 217], [303, 217]],
  [[267, 205], [305, 205]],
  [[271, 194], [308, 195]],
  [[276, 184], [310, 185]],
];

function mirrorPoint([x, y]: [number, number]): [number, number] {
  return [700 - x, y];
}

function mirrorPath(path: [number, number][]): [number, number][] {
  return path.map(mirrorPoint);
}

function pointsAttr(points: [number, number][]) {
  return points.map((p) => p.join(",")).join(" ");
}

export default function CoatingLayoutEndBit({
  hand,
  fullLengthRuns = 0,
  shoulderRuns = 0,
}: CoatingLayoutEndBitProps) {
  const isLH = hand === "LH";

  const outline = isLH ? RH_OUTLINE.map(mirrorPoint) : RH_OUTLINE;
  const holes = isLH ? RH_HOLES.map(mirrorPoint) : RH_HOLES;
  const fullRuns = isLH ? RH_FULL_LENGTH_RUNS.map(mirrorPath) : RH_FULL_LENGTH_RUNS;
  const shoulders = isLH ? RH_SHOULDER_RUNS.map(mirrorPath) : RH_SHOULDER_RUNS;

  const safeFullRuns = Math.max(0, Math.min(5, fullLengthRuns));
  const safeShoulderRuns = Math.max(0, Math.min(5, shoulderRuns));

  return (
    <div className="w-full overflow-x-auto">
      <svg
        viewBox="0 0 700 390"
        role="img"
        aria-label={`Dozer End Bit coating layout (${hand})`}
        className="min-w-[560px] w-full"
      >
        <text x="20" y="28" fontSize="16" fontWeight="600" fill={LINE_COLOUR}>
          Front Face View ({hand})
        </text>

        <polygon
          points={pointsAttr(outline)}
          fill={STEEL_FILL}
          stroke={LINE_COLOUR}
          strokeWidth="2"
        />

        {fullRuns.slice(0, safeFullRuns).map((path, i) => (
          <polyline
            key={`full-${i}`}
            points={pointsAttr(path)}
            fill="none"
            stroke={COATING_COLOUR}
            strokeWidth="8"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        ))}

        {shoulders.slice(0, safeShoulderRuns).map((path, i) => (
          <line
            key={`shoulder-${i}`}
            x1={path[0][0]}
            y1={path[0][1]}
            x2={path[1][0]}
            y2={path[1][1]}
            stroke={COATING_COLOUR}
            strokeWidth="8"
            strokeLinecap="round"
          />
        ))}

        {holes.map(([x, y], i) => (
          <circle
            key={`hole-${i}`}
            cx={x}
            cy={y}
            r={12}
            fill="white"
            stroke={LINE_COLOUR}
            strokeWidth="1.5"
          />
        ))}

        <g transform="translate(20 340)">
          <line x1="0" y1="0" x2="30" y2="0" stroke={COATING_COLOUR} strokeWidth="7" />
          <text x="38" y="4" fontSize="12" fill="#475569">
            Individual tungsten coating run
          </text>
        </g>

        <text x="20" y="365" fontSize="10" fontStyle="italic" fill="#94a3b8">
          Illustrative — actual end bit shape and hole configuration may differ from this generic template.
        </text>
      </svg>
    </div>
  );
}